### PR TITLE
(CMS-BOT/MU2E) TEST - IGNORE

### PR DESCRIPTION
**Pull request by ryuwd**
testing to see how cms-bot reacts after some fine tuning

### CODE REVIEW

**Comment by ryuwd** [comment]
Hi @ryuwd,
You have proposed changes to files in these packages:
- /
- TrackerConditions
- TrackerGeom
- CosmicAlignment
- CosmicReco

which require these tests: build, code checks.




<a href="https://mu2ewiki.fnal.gov/wiki/Jenkins">cms-bot/mu2e commands are explained here</a>

**Comment by ryuwd** [comment]
@ryuwd please run tests

**Comment by ryuwd** [comment]
The following tests have been triggered for ref https://github.com/ryuwd/Offline/pull/16/commits/a14adddf454c82dd238facd8d388496286a6aaa7: build, code checks

**Comment by ryuwd** [comment]
@ryuwd; please run validation, build, code checks

**Comment by ryuwd** [comment]
The following tests have been triggered for ref https://github.com/ryuwd/Offline/pull/16/commits/a14adddf454c82dd238facd8d388496286a6aaa7: validation

**Comment by ryuwd** [comment]
if the PR has a new commit, the bot should notice this when the result of the tests are published back on the thread, and mention that the 'test is out of date'

In addition, tests should not be triggered if they are still running for a previous commit

**Comment by ryuwd** [comment]
@ryuwd please run validation, build, code checks

**Comment by ryuwd** [comment]
The following tests have been triggered for ref https://github.com/ryuwd/Offline/pull/16/commits/47ff0ec04e0b79ee1b15e4ae424394efd9d83f19: validation

**Comment by ryuwd** [comment]
The following tests have been triggered for ref https://github.com/ryuwd/Offline/pull/16/commits/47ff0ec04e0b79ee1b15e4ae424394efd9d83f19: build, code checks

**Comment by ryuwd** [comment]
@ryuwd run tests

**Comment by ryuwd** [comment]
Those tests are still running for ref https://github.com/ryuwd/Offline/pull/16/commits/47ff0ec04e0b79ee1b15e4ae424394efd9d83f19! (build, code checks)

**Comment by ryunoneil** [comment]
@ryuwd; run tests

**Comment by ryuwd** [comment]
@ryuwd; run tests

**Comment by ryuwd** [comment]
Those tests are already run or are running for ref https://github.com/ryuwd/Offline/pull/16/commits/47ff0ec04e0b79ee1b15e4ae424394efd9d83f19! (build, code checks)

**Comment by ryuwd** [comment]
@ryuwd run tests   please

**Comment by ryuwd** [comment]
:x: Those tests are already run or are running for ref https://github.com/ryuwd/Offline/pull/16/commits/47ff0ec04e0b79ee1b15e4ae424394efd9d83f19 (build, code checks)

**Comment by ryuwd** [comment]
@ryuwd please test!

**Comment by ryuwd** [comment]
:hourglass: The following tests have been triggered for ref https://github.com/ryuwd/Offline/pull/16/commits/ed520fd9b2025d5ba205918fb0ca7dd366a37cfb: build, code checks

**Comment by ryuwd** [comment]
Error: A Jenkins job did not report output in the correct format. The output was as follows:
ed520fd9b2025d5ba205918fb0ca7dd366a37cfb
mu2e/codechecks
success
The comment_gh_pr.py script works!
:+1: The code check has passed.

**Comment by ryuwd** [comment]
:+1: The code check has passed.

**Comment by ryuwd** [comment]
:-1: The build failed :(
#### Tail of the logfile:
This is just a template.
#### Attachments:
- some links to jenkins job reports
- or something like that

**Comment by ryuwd** [comment]
@FNALbuild run build tests

**Comment by ryuwd** [comment]
@FNALbuild please test

**Pull request closed without merging**
